name: CI with GitHub Actions using Ant and JUnit | Â© 2023 minat.isleeping ğŸ¥±ğŸ’¤

# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

on:
  push:
    branches: [ main ] # Láº¥y code tá»« nhÃ¡nh main náº¿u cÃ³ ai push code lÃªn  
  pull_request:
    branches: [ main ] # Láº¥y code tá»« nhÃ¡nh main náº¿u cÃ³ ai gá»­i pull request  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: # Nhá»¯ng cÃ´ng viá»‡c dev lÃ m thÆ°á»ng ngÃ y: láº¥y code, build, cháº¡y test, Ä‘Ã³ng gÃ³i, gá»­i build...
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check-out repository # Láº¥y code tá»« kho tháº£y vÃ o mÃ¡y áº£o cá»§a GitHub chuáº©n bá»‹ build á»Ÿ bÆ°á»›c sau
        uses: actions/checkout@v3

      - name: Set up JDK 18 
        uses: actions/setup-java@v3 # Khai bÃ¡o cáº§n dÃ¹ng JDK Ä‘á»ƒ build
        with:
          java-version: '18' # Khai bÃ¡o sá»­ dá»¥ng phiÃªn báº£n JDK 18 Ä‘á»ƒ build
          distribution: 'temurin'
     
      - name: Build project with Ant
        run: ant -noinput -buildfile build.xml # QuÃ¡ trÃ¬nh build sáº½ cáº§n Ä‘áº¿n file cáº¥u hÃ¬nh build.xml, build-impl.xml
      
      - name: Distribute jar-war file # Gá»­i file .jar .war Ä‘i Ä‘Ã¢u, CD nháº£y vÃ o ...
        run: mkdir staging && cp dist/*.jar staging # táº¡o thÆ° má»¥c staging chá»©a file .jar .war sau khi build      
     
      - name: Make hyperlink to jar-war file # Táº¡o hyperlink Ä‘á»ƒ download build 
        uses: actions/upload-artifact@v1
        with:
          name: 1.0-SNAPSHOT.jar # Báº£n build Ä‘Æ°á»£c Ä‘Ã¡nh version 1.0-SNAPSHOT
          path: staging

# End of CI workflow file
